# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class ActionKind(str, Enum):
    Universal = "Universal"
    Energy = "Energy"
    Tool = "Tool"
    Transition = "Transition"
    Chance = "Chance"

class GateStatus(str, Enum):
    Open = "Open"
    Closed = "Closed"

class ItemKind(str, Enum):
    Tool = "Tool"
    Weapon = "Weapon"
    Food = "Food"
    Drink = "Drink"
    Key = "Key"
    Lore = "Lore"
    Material = "Material"

# #########################################################################
# Generated classes (8)
# #########################################################################

class Area(BaseModel):
    id: str
    name: str
    description: str
    actions: typing.List["AreaAction"] = Field(description='Must be objects, never bare strings')

class AreaAction(BaseModel):
    id: str
    label: str = Field(description='Plain English player-facing choice text')
    kind: ActionKind
    narrative: typing.Optional[str] = None
    energy_cost: typing.Optional[int] = None
    required_tool_id: typing.Optional[str] = None
    required_any_item_ids: typing.Optional[typing.List[str]] = None
    target_area_id: typing.Optional[str] = Field(default=None, description='Required when kind is transition')
    gate: typing.Optional["TransitionGate"] = None
    grant_item_id: typing.Optional[str] = None
    consume_item_id: typing.Optional[str] = None
    health_delta: typing.Optional[int] = None
    satiation_delta: typing.Optional[int] = None
    energy_delta: typing.Optional[int] = None
    unlock_action_ids: typing.Optional[typing.List[str]] = None
    set_flags: typing.Optional[typing.List[str]] = None
    require_flags: typing.Optional[typing.List[str]] = None
    forbid_flags: typing.Optional[typing.List[str]] = None
    once_flag: typing.Optional[str] = None
    advances_clock: typing.Optional[bool] = None
    ticks: typing.Optional[int] = None
    success_chance: typing.Optional[float] = Field(default=None, description='0-1 for chance actions')
    success: typing.Optional["ChanceOutcome"] = None
    failure: typing.Optional["ChanceOutcome"] = None
    show_chance: typing.Optional[bool] = None
    win: typing.Optional[bool] = Field(default=None, description='true ends the game as a win — use only on gated/late actions')
    lose: typing.Optional[bool] = None

class ChanceOutcome(BaseModel):
    narrative: str
    health_delta: typing.Optional[int] = None
    satiation_delta: typing.Optional[int] = None
    energy_delta: typing.Optional[int] = None
    target_area_id: typing.Optional[str] = None
    grant_item_id: typing.Optional[str] = None
    remove_item_ids: typing.Optional[typing.List[str]] = None
    set_flags: typing.Optional[typing.List[str]] = None
    unlock_action_ids: typing.Optional[typing.List[str]] = None
    win: typing.Optional[bool] = None
    lose: typing.Optional[bool] = None

class CharacterStats(BaseModel):
    health: int = Field(description='Starting health, typically 70-95')
    satiation: int = Field(description='Starting satiation, typically 55-85')
    energy: int = Field(description='Starting energy, typically 60-90')

class ClockConfig(BaseModel):
    satiation_loss_per_tick: int = Field(description='Usually 3-6')
    energy_gain_per_tick: int = Field(description='Usually 2-4')
    health_loss_per_tick: int = Field(description='Usually 4-6')

class Item(BaseModel):
    id: str = Field(description='Stable snake_case id referenced by actions')
    name: str
    kind: ItemKind
    description: str
    satiation_restore: typing.Optional[int] = Field(default=None, description='For food/drink; omit otherwise')
    energy_restore: typing.Optional[int] = Field(default=None, description='For food/drink; omit otherwise')
    health_restore: typing.Optional[int] = Field(default=None, description='For food/drink; omit otherwise')

class Scenario(BaseModel):
    title: str
    premise: str
    objective: str = Field(description='Clear multi-step goal in plain English')
    opening: str
    win_message: str
    lose_message: str
    start_area_id: str
    exit_area_ids: typing.List[str] = Field(description='Prefer empty []. Entering these areas wins immediately')
    character: "CharacterStats"
    clock: "ClockConfig"
    items: typing.List["Item"]
    areas: typing.List["Area"]

class TransitionGate(BaseModel):
    status: GateStatus = Field(description='closed means blocked until requirements met')
    requires_tool_id: typing.Optional[str] = None
    requires_any_item_ids: typing.Optional[typing.List[str]] = None
    energy_cost: typing.Optional[int] = None
    min_energy: typing.Optional[int] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (8)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
Area.model_rebuild()
AreaAction.model_rebuild()
ChanceOutcome.model_rebuild()
CharacterStats.model_rebuild()
ClockConfig.model_rebuild()
Item.model_rebuild()
Scenario.model_rebuild()
TransitionGate.model_rebuild()
