# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Area": types.Area,
    "stream_types.Area": stream_types.Area,

    "types.AreaAction": types.AreaAction,
    "stream_types.AreaAction": stream_types.AreaAction,

    "types.ChanceOutcome": types.ChanceOutcome,
    "stream_types.ChanceOutcome": stream_types.ChanceOutcome,

    "types.CharacterStats": types.CharacterStats,
    "stream_types.CharacterStats": stream_types.CharacterStats,

    "types.ClockConfig": types.ClockConfig,
    "stream_types.ClockConfig": stream_types.ClockConfig,

    "types.Item": types.Item,
    "stream_types.Item": stream_types.Item,

    "types.Scenario": types.Scenario,
    "stream_types.Scenario": stream_types.Scenario,

    "types.TransitionGate": types.TransitionGate,
    "stream_types.TransitionGate": stream_types.TransitionGate,


    "types.ActionKind": types.ActionKind,

    "types.GateStatus": types.GateStatus,

    "types.ItemKind": types.ItemKind,

}